export default [
	"Datawrapper",
	"Vercel",
	"Cohere",
	"Dabble",
	"Monogram",
	"Frontend Masters",
	"Hugging Face",
	"PQINA",
	"Raster",
	"Avast",
	"Threema Open Source Fund",
	"INVISR",
	"Matt",
	"Layer0",
	"Codesmith",
	"Metafy",
	"Jeff Moe",
	"Changelog",
	"Clancy Digital",
	"Kenoxa GmbH",
	"Level Up Tutorials",
	"The Pudding",
	"Jason Hetherington",
	"Zev Averbach"
];